ELF>`@�B@8 @$#@@@��UU ���-�=�=X`�-�=�=��888 XXXDDS�td888 P�td� � � DDQ�tdR�td�-�=�=HH/lib64/ld-linux-x86-64.so.2GNU�GNU,�rvP����]���c[a�rGNU��e�m? ![ j "libc.so.6printf_cxa_finalizelibc_start_mainGLIBC_2.2.5_ITM_deregisterTMCloneTablegmon_start_ITM_registerTMCloneTableui	3�=@�=@@�?�?�?�?�?�?��H��H��/H��t��H����5�/��%�/��h�����������%�/D����%u/D��1�I��^H��H���PTL��H� OH�=��R/��H�=y/H�r/H9�tH�./H��t	�����H�=I/H�5B/H)�H��H��?H��H�H��tH�/H��t��fD�����=/u+UH�=�.H��tH�=�.�����d�����.]������w�����UH��H�=��������H�=��������H�=�������H�=�������H�=�������]�f.���AWL�=�+AVI��AUI��ATA��UH�-�+SL)�H�������H��t1��L��L��D��A��H��H9�u�H��[]A\A]A^A�ff.������H��H���Size of a char: %i byte(s)
 ​Size of an int: %i byte(s)
 ​Size of a long int: %i byte(s)
 ​Size of a long long int: %i byte(s)
 ​Size of a float: %i byte(s)
 ;@|���t��������������\�����,��������4zRx�X���/D$4��� FJw�?:*3$"\����t���������}E�C tD�8���eF�I�E �E(�D0�H8�G@n8A0A(B BBB�`���@ H�=�=���o�p�
 ��?�(�	���o���o���o���o����o�=0@GCC: (Ubuntu 9.3.0-10ubuntu2) 9.3.0,I}�W.�I}��9W\IK�int+��lw�l�R�@�1$	�3e	6	�	�7	�	�8	�	�9	� 	�:	�(	i;	�0	�<	�8	=	�@	�@	�H	�A	�P	!B	�X	�D=`	�FCh	�Hep	�Iet	Jsx	4MP�	�NW�	�OI�	%QY�	Y �	N[d�	�\o�	6]C�	�^	G�	D_
 -�	�`e�	bu�D�
 +�8��Y 90K_�j�� 9���$����e�������1eI}�%:;9I$>$>I&I:;9	 :;9I8
 :;9<I !I/4:;9I?<!.?:;9'I@�Bj?� /home/emmanuel/Documents/ALX/Projects/alx-low_level_programming/0x00-hello_world/usr/lib/gcc/x86_64-linux-gnu/9/include/usr/include/x86_64-linux-gnu/bits/usr/include/x86_64-linux-gnu/bits/types/usr/include6-size.cstddef.htypes.hstruct_FILE.hFILE.hstdio.hsys_errlist.h	I�YYYY	YY_IO_buf_end_old_offsetsys_nerr_IO_save_end/home/emmanuel/Documents/ALX/Projects/alx-low_level_programming/0x00-hello_world/6-size.cshort intsize_t_IO_write_ptr_flags_IO_buf_base_markers_IO_read_end_freeres_buf/home/emmanuel/Documents/ALX/Projects/alx-low_level_programmingstderr_locklong int_cur_column_IO_FILEunsigned charGNU C17 9.3.0 -mtune=generic -march=x86-64 -g -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection_IO_marker_shortbuf_IO_write_base_unused2_IO_read_ptrshort unsigned intmain_freeres_list_pad5_IO_codecvtlong unsigned int_IO_write_endoff64_t_off_t_chain_IO_wide_data_IO_backup_basestdin_flags2_mode_IO_read_base_vtable_offset_IO_save_basesys_errlist_filenostdout_IO_lock_t8X|��p�
 (� @P`H � � �=�=�=�?@@ ����!7@F�=m@y�=�������!����=��=��=�� ��?�@ m @1@H8Lk@x �@� ��e�@q`/�@�I}�@� �"crtstuff.cderegister_tm_clones_do_global_dtors_auxcompleted.8059do_global_dtors_aux_fini_array_entryframe_dummyframe_dummy_init_array_entry6-size.cFRAME_END__init_array_end_DYNAMICinit_array_startGNU_EH_FRAME_HDR_GLOBAL_OFFSET_TABLE_libc_csu_fini_ITM_deregisterTMCloneTable_edataprintf@@GLIBC_2.2.5libc_start_main@@GLIBC_2.2.5data_startgmon_start__dso_handle_IO_stdin_usedlibc_csu_initbss_startmainTMC_END_ITM_registerTMCloneTable_cxa_finalize@@GLIBC_2.2.5.symtab.strtab.shstrtab.interp.note.gnu.property.note.gnu.build-id.note.ABI-tag.gnu.hash.dynsym.dynstr.gnu.version.gnu.version_r.rela.dyn.rela.plt.init.plt.got.plt.sec.text.fini.rodata.eh_frame_hdr.eh_frame.init_array.fini_array.dynamic.data.bss.comment.debug_aranges.debug_info.debug_abbrev.debug_line.debug_str#88 6XX$I|| W���o��$a���ipp�q���o��~���o �((��B���� �@@�PP�``��HH � ��� � D�� � ��=�-��=�-��=�-���?�/H@0@000$400)d05e3�C34nO0�5�8�"3	H?NAZ
